version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "production_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  rag_api:
    build:
      context: ./backend
      dockerfile: Dockerfile.yml
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - chromadb
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/production_db
      - CHROMA_URL=http://chromadb:8000

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.yml
    ports:
      - "8501:8501"
    depends_on:
      - rag_api
    environment:
      - RAG_API_URL=http://rag_api:8000

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1  # Ограничиваем параллелизм
      - OLLAMA_MAX_LOADED_MODELS=1


volumes:
  postgres_data:
  chroma_data:
  ollama_data: